# Generated by Django 6.0.3 on 2026-03-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
