# Generated by Django 6.0.3 on 2026-03-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_perfil_github_url_perfil_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='fecha',
        ),
        migrations.AddField(
            model_name='educacion',
            name='categoria',
            field=models.CharField(choices=[('profesional', 'Profesional'), ('formacion', 'Formación complementaria')], default='profesional', max_length=20),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='fecha_inicio',
            field=models.CharField(default='2024', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencia',
            name='fecha_termino',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
