# Generated by Django 6.0.3 on 2026-03-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_experiencia_fecha_educacion_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
